from handlers import client
from handlers import admin
from handlers import other
from handlers import casino_spin
from handlers import news_cybersport
from handlers import news_ixbt
from handlers import ls_message
from handlers import registration
from handlers import bonus_chy
from handlers import gif_random
from handlers import img_random
from handlers import search_wiki
from handlers import commands_list_menu
from handlers import info_profile_reply
from handlers import translate_p2p_chy
from handlers import translate_p2p_usd
from handlers import save_data_in_docx
